### PR TITLE
#67 add Google Analytics

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #44

### CODE REVIEW

**Comment by CAMOBAP** [comment]
Strange issue `google-analytics.html` must conform to those regexs https://github.com/jekyll/jekyll/blob/v4.3.2/lib/jekyll/tags/include.rb#L54

Locally it builds without issues

Investigation in progress

**Comment by CAMOBAP** [comment]
@ronaldtse could you please have a look

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP !

**Comment by ronaldtse** [comment]
Confirm this is fixed. Thanks!

**Pull request merged**
